# Generated by Django 5.2.8 on 2026-04-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.CharField(max_length=50)),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('member_type', models.CharField(choices=[('donor', 'দাতা সদস্য'), ('lifetime', 'আজীবন সদস্য'), ('general', 'সাধারণ সদস্য'), ('library', 'লাইব্রেরি সদস্য'), ('sports', 'ক্রীড়া সদস্য'), ('drama', 'নাট্যকলা সদস্য'), ('town', 'টাউন ক্লাব সদস্য'), ('child', 'শিশু চিত্রবিনোদন কেন্দ্র সদস্য')], max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/')),
            ],
        ),
    ]
