# Generated by Django 5.2.8 on 2026-04-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('donor_pdf', models.FileField(upload_to='voters/')),
                ('life_pdf', models.FileField(upload_to='voters/')),
                ('general_pdf', models.FileField(upload_to='voters/')),
            ],
        ),
    ]
