# Generated by Django 5.2.8 on 2026-05-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='signature',
        ),
    ]
