# Generated by Django 5.2.4 on 2026-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_photo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('field', 'Field Application'), ('leave', 'Leave Application')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='forms/')),
            ],
        ),
    ]
