# Generated by Django 5.2.8 on 2026-05-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0012_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='information',
            field=models.FileField(upload_to='publications/'),
        ),
    ]
