# Generated by Django 5.2.8 on 2026-05-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0013_alter_publication_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='information',
            field=models.FileField(upload_to='media_files/'),
        ),
    ]
