# Generated by Django 5.2.8 on 2026-04-23 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OldCommitteeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('president', 'সভাপতি গণের তালিকা'), ('secretary', 'সাধারণ সম্পাদক তালিকা'), ('drama', 'সম্পাদক, নাট্যকলা সংসদ'), ('sports', 'সম্পাদক, ক্রীড়া সংসদ'), ('library', 'সম্পাদক, লাইব্রেরি বিভাগ'), ('townclub', 'সম্পাদক, টাউন ক্লাব'), ('kids', 'সম্পাদক, শিশু চিকিৎসা কেন্দ্র')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OldCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='oldcommittee/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='oldcommittee.oldcommitteecategory')),
            ],
        ),
    ]
