# Generated by Django 5.2.8 on 2026-04-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('library', 'লাইব্রেরি বিভাগ'), ('sports', 'ক্রীড়া বিভাগ'), ('drama', 'নাট্যকলা সংসদ'), ('town', 'টাউন ক্লাব'), ('child', 'শিশু চিত্ত বিনোদন কেন্দ্র')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.JSONField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='divisions/')),
            ],
        ),
    ]
