# Generated by Django 5.2.8 on 2026-04-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='content',
            field=models.TextField(),
        ),
    ]
