# Generated by Django 5.2.8 on 2026-05-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('category_name_bangla', models.CharField(blank=True, max_length=200, null=True)),
                ('category_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book Category',
                'verbose_name_plural': 'Book Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='BookMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English')], max_length=20)),
                ('serial_no', models.PositiveIntegerField()),
                ('book_code', models.CharField(max_length=50, unique=True)),
                ('book_addition_number', models.CharField(max_length=100)),
                ('book_addition_date', models.DateField()),
                ('book_name', models.CharField(max_length=500)),
                ('author_name', models.CharField(blank=True, max_length=300, null=True)),
                ('editor_name', models.CharField(blank=True, max_length=300, null=True)),
                ('translator_name', models.CharField(blank=True, max_length=300, null=True)),
                ('call_no', models.CharField(max_length=100)),
                ('isbn_number', models.CharField(blank=True, max_length=100, null=True)),
                ('copy_no', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher_name', models.CharField(blank=True, max_length=300, null=True)),
                ('place_of_publication', models.CharField(blank=True, max_length=300, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('book_page_no', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('ক্রয়', 'ক্রয়'), ('উপহার', 'উপহার')], max_length=20)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('floor_no', models.CharField(blank=True, max_length=50, null=True)),
                ('cupboard', models.CharField(blank=True, max_length=50, null=True)),
                ('rack_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bar_code', models.CharField(max_length=150, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.bookcategory')),
            ],
            options={
                'verbose_name': 'Book Master',
                'verbose_name_plural': 'Book Master',
                'ordering': ['version', 'serial_no'],
                'unique_together': {('version', 'serial_no')},
            },
        ),
    ]
