# Generated by Django 5.2.8 on 2026-05-16 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'ordering': ['category_code'], 'verbose_name': 'Book Category', 'verbose_name_plural': 'Book Categories'},
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='book.bookcategory'),
        ),
        migrations.AddField(
            model_name='bookmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookmaster',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='category_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='category_name_bangla',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddIndex(
            model_name='bookcategory',
            index=models.Index(fields=['category_code'], name='book_bookca_categor_1aa7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcategory',
            index=models.Index(fields=['category_name'], name='book_bookca_categor_6dbc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcategory',
            index=models.Index(fields=['category_name_bangla'], name='book_bookca_categor_ba250d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmaster',
            index=models.Index(fields=['version', 'serial_no'], name='book_bookma_version_66774a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmaster',
            index=models.Index(fields=['book_code'], name='book_bookma_book_co_ca87a4_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmaster',
            index=models.Index(fields=['bar_code'], name='book_bookma_bar_cod_6745b4_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmaster',
            index=models.Index(fields=['book_name'], name='book_bookma_book_na_108c24_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmaster',
            index=models.Index(fields=['author_name'], name='book_bookma_author__36834d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmaster',
            index=models.Index(fields=['isbn_number'], name='book_bookma_isbn_nu_16b372_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmaster',
            index=models.Index(fields=['call_no'], name='book_bookma_call_no_d5b6cb_idx'),
        ),
    ]
