# Generated by Django 5.2.4 on 2026-04-24 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_oldcommitteedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCommitteeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('library', 'লাইব্রেরি বিভাগ'), ('sports', 'ক্রীড়া বিভাগ'), ('drama', 'নাট্যকলা সংসদ'), ('town', 'টাউন ক্লাব'), ('issue', 'ইস্যু বিভাগ')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCommitteeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='subcommittee_pdfs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='committee.subcommitteecategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='subcommittee/')),
                ('role_type', models.CharField(choices=[('head', 'Head'), ('member', 'Member')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='committee.subcommitteecategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
