# Generated by Django 5.2.4 on 2026-04-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0004_alter_subcommitteecategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcommitteecategory',
            name='type',
            field=models.CharField(choices=[('library', 'লাইব্রেরি বিভাগ'), ('sports', 'ক্রীড়া বিভাগ'), ('drama', 'নাট্যকলা সংসদ'), ('town', 'টাউন ক্লাব'), ('issue', 'ইস্যু বিভাগ')], max_length=50, unique=True),
        ),
    ]
