# Generated by Django 5.2.8 on 2026-04-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0005_alter_subcommitteecategory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('president', 'সভাপতি'), ('secretary', 'সাধারণ সম্পাদক')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='committee/')),
            ],
        ),
    ]
