# Generated by Django 5.2.8 on 2026-05-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0006_executivecommittee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemember',
            old_name='role',
            new_name='committee_role',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='role_type',
        ),
        migrations.AddField(
            model_name='committeemember',
            name='member_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='member_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
