# Generated by Django 5.2.8 on 2026-05-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0007_rename_role_committeemember_committee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
