# Generated by Django 5.2.8 on 2026-05-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0008_committeemember_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemember',
            name='title',
        ),
    ]
