# Generated by Django 5.2.8 on 2026-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0010_committee_committeemember_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
