# Generated by Django 5.2.8 on 2026-05-10 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0011_committee_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='subcommitteecategory',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='subcommitteemember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subcommitteemember',
            name='role',
        ),
        migrations.RemoveField(
            model_name='subcommitteemember',
            name='role_type',
        ),
        migrations.AddField(
            model_name='subcommitteecategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcommitteemember',
            name='member_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subcommitteemember',
            name='member_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subcommitteemember',
            name='member_role',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subcommitteecategory',
            name='type',
            field=models.CharField(choices=[('library', 'লাইব্রেরি বিভাগ'), ('sports', 'ক্রীড়া বিভাগ'), ('drama', 'নাট্যকলা সংসদ'), ('town', 'টাউন ক্লাব'), ('issue', 'ইস্যু বিভাগ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subcommitteemember',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='committee.subcommitteecategory'),
        ),
        migrations.AlterField(
            model_name='subcommitteemember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcommittee/'),
        ),
        migrations.AddField(
            model_name='subcommitteecategory',
            name='subcommittee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='committee.subcommittee'),
        ),
    ]
