# Generated by Django 5.2.8 on 2026-05-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0012_subcommittee_alter_subcommitteecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivecommittee',
            name='details',
            field=models.TextField(blank=True, help_text='Small details/designation under the name', null=True),
        ),
    ]
