# Generated by Django 5.2.8 on 2026-05-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0013_executivecommittee_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('general', 'সাধারণ বিভাগ'), ('library', 'লাইব্রেরি বিভাগ'), ('sports', 'ক্রীড়া সংসদ'), ('drama', 'নাট্যকলা সংসদ')], max_length=50)),
                ('serial', models.PositiveIntegerField()),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employees/')),
            ],
        ),
    ]
